stages:
  - build

rust-latest:
  stage: build
  image: rust:latest
  before_script:
    - rustup component add rustfmt
  script:
    - cargo build --verbose
    - cargo test --verbose
    - cargo fmt --all -- --check